const beachImages=[
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/04/120.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"Yarada_Beach",
    },
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2019/02/FotoJet-21.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"Rishikonda_Beach"
    },
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2019/02/FotoJet-19.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"Bheemili_Beach"
    },
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2019/02/FotoJet-17.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"Lawson’s_Bay_Beach"
    },
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2019/10/sagar-nagar-beach.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"Sagar_Nagar_Beach"
    }
];

const religiousImages=[
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/04/315.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"Kailasagiri"
    },
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/04/109.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"Simhachalam_Temple"
    },
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2019/02/FotoJet-20.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"Sea_War_Memorial"
    },
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2019/02/Visakha-Museum.jpeg",
        middleclass:"middle1",
        textclass:"text",
        name:"Visakha_Museum"
    },
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2019/02/Bojjannakonda.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"Bojjannakonda"
    },
    {
        className:"container2",        
        divclass:"places1",
        src:"https://images.thrillophilia.com/image/upload/s--Zy9mXYSN--/c_fill,dpr_1.0,f_auto,fl_strip_profile,g_center,h_450,q_auto,w_753/v1/images/photos/000/039/934/original/1525778950_Salar_Jung_Museum.jpg.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"salar_jung_museum"
    },
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2020/07/Thotlakondat.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"Thotlakonda_Complex"
    }
];

const touristImages=[
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/04/510.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"Submarine_Museum"
    },
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/04/78.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"Indira_Gandhi_Park"
    },
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/04/88.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"VUDA Park"
    },
    {
        className:"container2",        
        divclass:"places1",
        src:"https://img.traveltriangle.com/blog/wp-content/tr:w-700,h-400/uploads/2018/04/97.jpg",
        middleclass:"middle1",
        textclass:"text",
        name:"Dolphin’s_Nose"
    }
];
export {touristImages,religiousImages,beachImages};